project_id = "rlsfgqeppzctlftlbkft"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.fitness-agent]
verify_jwt = false

[functions.food-scanner]
verify_jwt = false

[functions.health-report]
verify_jwt = false

[functions.report-ocr]
verify_jwt = false

[functions.symptom-checker]
verify_jwt = false
